# Generated by Django 3.2.7 on 2021-10-07 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='course',
            name='unique_course_index_constraint',
        ),
        migrations.RemoveConstraint(
            model_name='student',
            name='unique student index constraint',
        ),
        migrations.RemoveIndex(
            model_name='course',
            name='course_index',
        ),
        migrations.RemoveIndex(
            model_name='student',
            name='student_index',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='upload_date',
            new_name='upload_set',
        ),
        migrations.RenameField(
            model_name='enrolment',
            old_name='upload_date',
            new_name='upload_set',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='upload_date',
            new_name='upload_set',
        ),
        migrations.AlterField(
            model_name='uploadset',
            name='course_data_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='uploadset',
            name='person_data_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='uploadset',
            name='transfer_data_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['course_code', 'section', 'upload_set'], name='course_index'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['student_number', 'upload_set'], name='student_index'),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.UniqueConstraint(fields=('course_code', 'section', 'upload_set'), name='unique_course_index_constraint'),
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.UniqueConstraint(fields=('student_number', 'upload_set'), name='unique student index constraint'),
        ),
    ]
