# Generated by Django 3.2.7 on 2021-10-24 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0002_auto_20211019_0842'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreReq',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('course_code', models.CharField(max_length=10)),
            ],
        ),
    ]
