# Generated by Django 3.2.7 on 2021-10-07 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0002_auto_20211007_1436'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrolment',
            old_name='course_id',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='enrolment',
            old_name='student_id',
            new_name='student',
        ),
    ]
