# Generated by Django 3.2.7 on 2021-10-25 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0003_prereq'),
    ]

    operations = [
        migrations.AddField(
            model_name='prereq',
            name='rank',
            field=models.CharField(default='FIR', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='rank',
            field=models.CharField(default='FIR', max_length=3),
            preserve_default=False,
        ),
    ]
