# Generated by Django 3.2.7 on 2021-10-27 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0004_auto_20211025_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='rank',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
