# Generated by Django 3.2.7 on 2021-10-27 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0004_auto_20211025_2017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='email',
        ),
    ]
