# Generated by Django 3.2.7 on 2021-10-04 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('credit_hours', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CourseSection',
            fields=[
                ('section', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('course_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudentTrackingSystemApp.course')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('sid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=70)),
                ('gender', models.CharField(max_length=1)),
                ('address', models.TextField(max_length=140)),
                ('email', models.EmailField(max_length=50)),
                ('campus', models.CharField(max_length=2)),
                ('program', models.CharField(max_length=10)),
                ('start_date', models.DateField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Enrolment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=10)),
                ('grade', models.CharField(max_length=5)),
                ('course_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudentTrackingSystemApp.coursesection')),
                ('sid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudentTrackingSystemApp.student')),
            ],
        ),
        migrations.AddConstraint(
            model_name='enrolment',
            constraint=models.UniqueConstraint(fields=('sid', 'course_section'), name='unique enrolment key'),
        ),
    ]
