# Generated by Django 3.2.7 on 2021-11-28 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='course',
            name='unique_course_index_constraint',
        ),
        migrations.RemoveIndex(
            model_name='course',
            name='course_index',
        ),
        migrations.AlterField(
            model_name='enrolment',
            name='grade',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['course_code', 'section', 'upload_set', 'name', 'credit_hours'], name='course_index'),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.UniqueConstraint(fields=('course_code', 'section', 'upload_set', 'name', 'credit_hours'), name='unique_course_index_constraint'),
        ),
    ]
