# Generated by Django 3.2.7 on 2021-11-15 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0002_course_course_type'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='enrolment',
            name='unique_enrolment_constraint',
        ),
        migrations.AlterField(
            model_name='student',
            name='campus',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.TextField(max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='program',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='start_date',
            field=models.DateField(max_length=8, null=True),
        ),
        migrations.AddConstraint(
            model_name='enrolment',
            constraint=models.UniqueConstraint(fields=('student_id', 'course_id', 'term'), name='unique_enrolment_constraint'),
        ),
    ]
