# Generated by Django 3.2.7 on 2021-12-01 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0003_student_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course_type',
        ),
    ]
